language: haskell

before_install:
  - git clone https://github.com/guillaume-nargeot/hpc-coveralls.git
  - cd hpc-coveralls
#  - cabal install
  - chmod +x run-cabal-test.sh
  - chmod +x hpc-coveralls.sh
  - chmod +x dummy-success-exit-script.sh
  - cd ..

script:
  - cabal configure --enable-tests --enable-library-coverage
  - cabal build
  - hpc-coveralls/run-cabal-test.sh

after_script:
  - hpc-coveralls/hpc-coveralls.sh 
