language: haskell

before_install:
  - git clone https://github.com/guillaume-nargeot/hpc-coveralls.git
  - cd hpc-coveralls
  - cabal install
  - cd ..
  - sudo apt-get -q -y install hlint || cabal install hlint

script:
  - hlint . --ignore="Parse error"
  - cabal configure --enable-tests --enable-library-coverage
  - cabal build
  - hpc-coveralls/run-cabal-test.sh --show-details=always

after_script:
  - hpc-coveralls/hpc-coveralls.sh test-all
