language: haskell

ghc: 7.8

before_install:
  - sudo apt-get -q -y install hlint || cabal install hlint
  - sudo apt-get install llvm-dev
  - cabal install --only-dependencies --enable-tests -f -llvm

script:
  - hlint . --ignore="Parse error"
  - cabal configure --enable-tests --enable-library-coverage
  - cabal build
  - cabal test --show-details=always

after_script:
  - cabal install hpc-coveralls
  - hpc-coveralls --coverage-mode=StrictlyFullLines --exclude-dir=test test-all
