language: haskell

before_install:
  - git clone https://github.com/guillaume-nargeot/hpc-coveralls.git
  - cd hpc-coveralls
  - cabal install
  - chmod +x run-cabal-test.sh
  - chmod +x hpc-coveralls.sh
  - cd ..
  - sudo apt-get -q -y install hlint || cabal install hlint

script:
  - hlint --ignore="Parse error" src/ test/
  - cabal configure --enable-tests --enable-library-coverage
  - cabal build
  - hpc-coveralls/run-cabal-test.sh

after_script:
  - hpc-coveralls/hpc-coveralls.sh project-euler-0.1.0.0
